### ISSUE TITLE
Improve wording for question id=44

### ISSUE THREAD

**Issue by Talkless** [SapplyValues/SapplyValues.github.io#11]
Questio with id=44 is:
> Parents should hold absolute power over their children, as they are older and more experienced

"as they are older", maybe means "as children _gets_ older"? Meaning, even if children gets older, parents should (still) hold absolute power?

While running the test I assumed "because parents are older", but it made me to doubt question meaning a little bit. Maybe this could be improved a bit?

P.S. I'm not native English speaker.

**Comment by CIA-256** [comment]
It is meant as parental authority over children, since parents are older and have experience. But I would be willing to accept alternative wordings.
