### ISSUE TITLE
This isn't a bug report

### ISSUE THREAD

**Issue by endolith** [SapplyValues/SapplyValues.github.io#3]
Just making you aware of [this comment](https://github.com/swoodmood/Sapplycompass/issues/2#issuecomment-586569487) by the original author, who disavows the content of the quiz:

> You should know the entire site was made as a piece of propaganda for the Stalinist cult I was part of at 15, to prove authoritarian leftists didn't hate minorities. It was never intended to be good

😀

**Comment by ghost** [comment]
Yeah I'm aware of this. Still, clearly a lot of people like it. My goal was just to improve the UI, not to comment on the contents of the quiz.
