### ISSUE TITLE
Not clear that you have to press Enter for text input fields

### ISSUE THREAD

**Issue by endolith** [SapplyValues/SapplyValues.github.io#4]
For the "what do you consider yourself" and "age" fields, it's not clear that you have to push Enter after typing in order to get the "Submit" button to appear.  It should probably just be there always, grayed out at first, and become pressable after you've typed something.

**Comment by ghost** [comment]
Resolved in 5bba615be45e6fd93056bb051bd18d7bf7babd55, 03d8c5bf63cd43da488a057201827b0b9e1d2b62
